basePath: /api
definitions:
  http.UserCreateDto:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  http.UserResponseDto:
    properties:
      createdAt:
        type: string
      deletedAt:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  title: Swagger GO Example App API
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: UserCreateDto JSON
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/http.UserCreateDto'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/http.UserResponseDto'
      summary: Create new user
      tags:
      - users
swagger: "2.0"
