name: "Build app and run tests"

on:
 pull_request:
   branches: [main]

env:
  GO_ENV: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19.4"
      
      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...  

      - name: Run go vet
        run: go vet ./...

      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0

      - name: Run tests
        run: |
          go install github.com/rubenv/sql-migrate/...@latest
          sql-migrate up
          go test -v ./...
