name: "Build App"

on:
 pull_request:
   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.19.4"
      
      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...  


